version: "3.9"

services:
  back-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: marketplace_back_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./back:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_URL: http://localhost:8000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: marketplace
      DB_USERNAME: marketplace
      DB_PASSWORD: marketplace

      REDIS_HOST: redis
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "no-reply@example.com"
      MAIL_FROM_NAME: "Marketplace"

    depends_on:
      - postgres
      - redis
      - mailpit

  back-queue:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: marketplace_back_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./back:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: marketplace
      DB_USERNAME: marketplace
      DB_PASSWORD: marketplace
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - back-app
      - postgres
      - redis

  back-nginx:
    build:
      context: ./back/docker/nginx
      dockerfile: Dockerfile
    container_name: marketplace_back_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - back-app
    volumes:
      - ./back:/var/www/html

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: marketplace_front
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - back-nginx


  postgres:
    image: postgres:16-alpine
    container_name: marketplace_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: marketplace_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret123
    ports:
      - "5050:80"
    depends_on:
      - postgres


  redis:
    image: redis:7-alpine
    container_name: marketplace_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: marketplace_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
    environment:
      MP_SMTP_BIND_ADDR: "0.0.0.0:1025"
      MP_API_BIND_ADDR: "0.0.0.0:8025"

volumes:
  db_data:
